# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Windows Client

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Upload MSI
      uses: actions/upload-artifact@v4
      with:
        name: MSI file
        path: target/installer/*.msi
